services:
  netpilot-db:
    image: postgres:latest
    container_name: netpilot-db
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - netpilot-db-data:/var/lib/postgresql/data

volumes:
  netpilot-db-data:
    driver: local
